export interface QuestItem {
  id: number;
  quest: string;
  duplication: boolean;
  option: string[];
  notice: string;
}

export const questionList = [
  {
    id: 1,
    quest: '지원받고 싶은 정부지원사업의 사업유형을 선택해주세요.',
    duplication: true,
    option: [
      '사업화',
      'R&D',
      '시설/공간/보육',
      '멘토링/컨설팅',
      '행사/네트워크',
      '융자',
      '인력',
      '글로벌',
    ],
    notice:
        '각 사업유형에 대해 자세하게 알고 싶다면 아래의 링크를 클릭해보세요.(링크 주소~)',
  },
  {
    id: 2,
    quest: '본인의 아이템과 관련있는 키워드를 선택해주세요.',
    duplication: true,
    option: [
      '해당없음',
      '4차산업혁명',
      'SW',
      '기술창업(기술을 보유, 혁신 기술)',
      'ICT(ICT 기반 융복합분야)',
      '데이터(Data)',
      'Network',
      '인공지능(AI)',
      '공공기술',
      '공간정보',
      '소재',
      '부품',
      '장비',
      '예술',
      '콘텐츠',
      '바이오',
      '헬스',
      '스포츠',
      '농업',
      '농촌',
      '식품',
      '보건',
      '해양수산',
      '전통문화',
      '녹색',
      '산림',
      '로컬크리에이터',
      '물산업',
      '관광',
    ],
    notice: '',
  },
  {
    id: 3,
    quest: '본인의 아이템과 관련있는 키워드를 선택해주세요.(중복가능)',
    duplication: true,
    option: [
      '해당없음',
      '바이오',
      '헬스',
      '스포츠',
      '농업',
      '농촌',
      '식품',
      '보건',
      '해양수산',
      '전통문화',
      '녹색',
      '산림',
      '로컬크리에이터',
      '물산업',
      '관광',
    ],
    notice: '',
  },
  {
    id: 4,
    quest: '본인의 아이템과 관련있는 키워드를 선택해주세요.(중복가능)',
    duplication: true,
    option: ['해당없음', '글로벌(해외, 현지매출)', '사회적', '비대면'],
    notice: '',
  },
  {
    id: 5,
    quest: '현재 보유하고 있는 것을 선택해주세요.(중복가능)',
    duplication: true,
    option: ['해당없음', '특허권(특허)', '품종보호권', '지식재산권'],
    notice: '선택하면 개수 입력 창 생기게 하기',
  },
  {
    id: 6,
    quest: '폐업한 경험이 있나요?(중복불가)',
    duplication: false,
    option: ['O(재창업)', 'X'],
    notice:
        'X인 경우 ‘장애’가 들어간 행 제외하고 재창업 관련 키워드가 들어간 행 모두 제거',
  },
  {
    id: 7,
    quest: '사업자등록을 한적이 있나요? ※개인사업자, 법인 모두 포함 (중복불가)',
    duplication: false,
    option: ['O', 'X(생애최초)'],
    notice: 'O인 경우 생애최초가 들어간 행 모두 제거',
  },
  {
    id: 8,
    quest: '사업자등록을 한적이 있나요? ※개인사업자, 법인 모두 포함 (중복불가)',
    duplication: false,
    option: ['O', 'X(생애최초)'],
    notice: 'O인 경우 생애최초가 들어간 행 모두 제거',
  },
  {
    id: 9,
    quest: '사업자등록을 한적이 있나요? ※개인사업자, 법인 모두 포함 (중복불가)',
    duplication: false,
    option: ['O', 'X(생애최초)'],
    notice: 'O인 경우 생애최초가 들어간 행 모두 제거',
  },
  {
    id: 10,
    quest: '사업자등록을 한적이 있나요? ※개인사업자, 법인 모두 포함 (중복불가)',
    duplication: false,
    option: ['O', 'X(생애최초)'],
    notice: 'O인 경우 생애최초가 들어간 행 모두 제거',
  },
  {
    id: 11,
    quest: '사업자등록을 한적이 있나요? ※개인사업자, 법인 모두 포함 (중복불가)',
    duplication: false,
    option: ['O', 'X(생애최초)'],
    notice: 'O인 경우 생애최초가 들어간 행 모두 제거',
  },
  {
    id: 12,
    quest: '사업자등록을 한적이 있나요? ※개인사업자, 법인 모두 포함 (중복불가)',
    duplication: false,
    option: ['O', 'X(생애최초)'],
    notice: 'O인 경우 생애최초가 들어간 행 모두 제거',
  },
  {
    id: 13,
    quest: '사업자등록을 한적이 있나요? ※개인사업자, 법인 모두 포함 (중복불가)',
    duplication: false,
    option: ['O', 'X(생애최초)'],
    notice: 'O인 경우 생애최초가 들어간 행 모두 제거',
  }, {
    id: 14,
    quest: '사업자등록을 한적이 있나요? ※개인사업자, 법인 모두 포함 (중복불가)',
    duplication: false,
    option: ['O', 'X(생애최초)'],
    notice: 'O인 경우 생애최초가 들어간 행 모두 제거',
  }, {
    id: 15,
    quest: '사업자등록을 한적이 있나요? ※개인사업자, 법인 모두 포함 (중복불가)',
    duplication: false,
    option: ['O', 'X(생애최초)'],
    notice: 'O인 경우 생애최초가 들어간 행 모두 제거',
  },
  {
    id: 16,
    quest: '사업자등록을 한적이 있나요? ※개인사업자, 법인 모두 포함 (중복불가)',
    duplication: false,
    option: ['O', 'X(생애최초)'],
    notice: 'O인 경우 생애최초가 들어간 행 모두 제거',
  },
  {
    id: 17,
    quest: '사업자등록을 한적이 있나요? ※개인사업자, 법인 모두 포함 (중복불가)',
    duplication: false,
    option: ['O', 'X(생애최초)'],
    notice: 'O인 경우 생애최초가 들어간 행 모두 제거',
  },
  {
    id: 18,
    quest: '사업자등록을 한적이 있나요? ※개인사업자, 법인 모두 포함 (중복불가)',
    duplication: false,
    option: ['O', 'X(생애최초)'],
    notice: 'O인 경우 생애최초가 들어간 행 모두 제거',
  },
  {
    id: 19,
    quest: '사업자등록을 한적이 있나요? ※개인사업자, 법인 모두 포함 (중복불가)',
    duplication: false,
    option: ['O', 'X(생애최초)'],
    notice: 'O인 경우 생애최초가 들어간 행 모두 제거',
  },
  {
    id: 20,
    quest: '사업자등록을 한적이 있나요? ※개인사업자, 법인 모두 포함 (중복불가)',
    duplication: false,
    option: ['O', 'X(생애최초)'],
    notice: 'O인 경우 생애최초가 들어간 행 모두 제거',
  },
  {
    id: 21,
    quest: '사업자등록을 한적이 있나요? ※개인사업자, 법인 모두 포함 (중복불가)',
    duplication: false,
    option: ['O', 'X(생애최초)'],
    notice: 'O인 경우 생애최초가 들어간 행 모두 제거',
  },
  {
    id: 22,
    quest: '사업자등록을 한적이 있나요? ※개인사업자, 법인 모두 포함 (중복불가)',
    duplication: false,
    option: ['O', 'X(생애최초)'],
    notice: 'O인 경우 생애최초가 들어간 행 모두 제거',
  },


];
